### ISSUE TITLE
Encourage use of partial and lambda?

### ISSUE THREAD

**Issue by astrojuanlu** [astrojuanlu/scipy#4]
It's somewhat disappointing when you see inconsistent handling of _args and *_kwargs across SciPy. For example `ode` and `odeint` accept only *args for user-supplied methods. But the passing of extra parameters is actually a solved problem using lambdas or functools.partial.

In MATLAB this is the new method they are encouraging (see http://www.mathworks.nl/matlabcentral/newsreader/view_thread/308285#837860).

**Comment by Juanlu001** [comment]
lambdas in Python are disgusting anyways.
